
import React, { useState, useEffect } from 'react';
import { GoogleGenAI } from '@google/genai';
import { Show } from '../types';
import { useTranslation } from 'react-i18next';
// FIX: Removed incorrect import of SparklesIcon and unused InfoIcon from constants 
// as a local Sparkles component is defined and used instead.

interface AIAnalysisProps {
    show: Show;
}

// Sparkles Icon component
const Sparkles = ({ className }: { className?: string }) => (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" className={className || "w-5 h-5"}>
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
    </svg>
);

const AIAnalysis: React.FC<AIAnalysisProps> = ({ show }) => {
    const { t, i18n } = useTranslation();
    const [analysis, setAnalysis] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(false);

    const fetchAnalysis = async () => {
        if (!process.env.API_KEY || loading) return;
        
        setLoading(true);
        setError(false);

        try {
            const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
            const prompt = `Analyze the ${show.media_type === 'movie' ? 'movie' : 'TV show'} "${show.title}" (${show.year}). 
            Based on its genres (${show.genres?.join(', ')}), provide a concise 3-point bulleted list in ${i18n.language} explaining:
            1. What makes it unique compared to other titles in its genre.
            2. The type of mood/vibe it fits (e.g. "perfect for a rainy night").
            3. Who would enjoy it most (target audience).
            Keep it objective, engaging, and avoid spoilers.`;

            const response = await ai.models.generateContent({
                model: 'gemini-3-flash-preview',
                contents: prompt,
                config: {
                    temperature: 0.7,
                    topP: 0.8,
                    topK: 40
                }
            });

            if (response.text) {
                setAnalysis(response.text);
            } else {
                throw new Error("No response from AI");
            }
        } catch (err) {
            console.error("AI Analysis error:", err);
            setError(true);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        setAnalysis(null); // Reset when show changes
    }, [show.id]);

    if (!process.env.API_KEY) return null;

    return (
        <div className="bg-gradient-to-br from-indigo-50 to-blue-50 dark:from-indigo-900/10 dark:to-blue-900/10 rounded-2xl p-6 border border-indigo-100 dark:border-indigo-800/50 shadow-sm overflow-hidden relative group">
            <div className="flex items-center gap-2 mb-4">
                <Sparkles className="text-indigo-600 dark:text-brand-primary w-5 h-5 animate-pulse" />
                <h3 className="text-lg font-bold text-gray-900 dark:text-white">AI Show Insights</h3>
            </div>

            {analysis ? (
                <div className="prose prose-sm dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 animate-fade-in">
                    <div className="whitespace-pre-line leading-relaxed">
                        {analysis}
                    </div>
                    <p className="text-[10px] text-gray-400 mt-4 italic">
                        Insights generated by Gemini AI. Accuracy may vary.
                    </p>
                </div>
            ) : (
                <div className="flex flex-col items-center justify-center py-6 text-center">
                    {loading ? (
                        <div className="flex flex-col items-center gap-3">
                            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600 dark:border-brand-primary"></div>
                            <p className="text-sm text-gray-500 animate-pulse font-medium">Gemini is analyzing "{show.title}"...</p>
                        </div>
                    ) : (
                        <>
                            <p className="text-sm text-gray-600 dark:text-gray-400 mb-4 max-w-xs">
                                Want a quick, smart breakdown of why you should watch this?
                            </p>
                            <button 
                                onClick={fetchAnalysis}
                                className="px-6 py-2 bg-indigo-600 dark:bg-brand-primary text-white dark:text-black rounded-full text-sm font-bold shadow-md hover:shadow-indigo-500/20 dark:hover:shadow-brand-primary/20 transition-all transform hover:-translate-y-0.5 active:translate-y-0"
                            >
                                Generate AI Insights
                            </button>
                        </>
                    )}
                    {error && !loading && (
                        <p className="mt-3 text-xs text-red-500 font-medium">Failed to reach AI consultant. Try again later.</p>
                    )}
                </div>
            )}
        </div>
    );
};

export default AIAnalysis;
