
import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { SUPPORTED_LANGUAGES, getLocalizedPath } from '../lib/routeUtils';

export const useSEO = (title?: string, description?: string, image?: string, imageAlt?: string, skipSuffix: boolean = false) => {
    const { t, i18n } = useTranslation();

    useEffect(() => {
        // Fallbacks using translations
        const defaultTitle = t('seo.default_title');
        const defaultDesc = t('seo.default_desc');

        // 1. Set Document Title
        const originalTitle = document.title;
        let newTitle = defaultTitle;
        
        if (title) {
            newTitle = skipSuffix ? title : `${title} | Watchlistey`;
        }
        
        document.title = newTitle;

        // 2. Set Meta Description
        let metaDesc = document.querySelector("meta[name='description']");
        if (!metaDesc) {
            metaDesc = document.createElement('meta');
            metaDesc.setAttribute('name', 'description');
            document.head.appendChild(metaDesc);
        }
        const originalDesc = metaDesc.getAttribute('content');
        
        const finalDesc = description || defaultDesc;
        // Truncate to ~160 chars for optimal SEO
        metaDesc.setAttribute('content', finalDesc.substring(0, 160));

        // 3. Set Canonical URL & Hreflang Tags
        let linkCanonical = document.querySelector("link[rel='canonical']");
        if (!linkCanonical) {
            linkCanonical = document.createElement('link');
            linkCanonical.setAttribute('rel', 'canonical');
            document.head.appendChild(linkCanonical);
        }
        const originalCanonical = linkCanonical.getAttribute('href');
        linkCanonical.setAttribute('href', window.location.href);

        // HREFLANG
        const existingHreflangs = document.querySelectorAll("link[rel='alternate'][hreflang]");
        existingHreflangs.forEach(el => el.remove());

        const currentPath = window.location.pathname;
        const origin = window.location.origin;

        SUPPORTED_LANGUAGES.forEach(lang => {
            const link = document.createElement('link');
            link.setAttribute('rel', 'alternate');
            link.setAttribute('hreflang', lang);
            // Construct full absolute URL for the localized version
            const localizedPath = getLocalizedPath(currentPath, lang);
            link.setAttribute('href', `${origin}${localizedPath}`);
            document.head.appendChild(link);
        });

        // Add x-default (usually English)
        const xDefaultLink = document.createElement('link');
        xDefaultLink.setAttribute('rel', 'alternate');
        xDefaultLink.setAttribute('hreflang', 'x-default');
        const defaultPath = getLocalizedPath(currentPath, 'en');
        xDefaultLink.setAttribute('href', `${origin}${defaultPath}`);
        document.head.appendChild(xDefaultLink);


        // 4. Set Open Graph Tags (Social Sharing)
        const setMetaTag = (property: string, content: string) => {
            let tag = document.querySelector(`meta[property='${property}']`);
            if (!tag) {
                tag = document.createElement('meta');
                tag.setAttribute('property', property);
                document.head.appendChild(tag);
            }
            tag.setAttribute('content', content);
            return tag;
        };

        setMetaTag('og:title', newTitle);
        setMetaTag('og:description', finalDesc.substring(0, 200));
        if (image) {
            setMetaTag('og:image', image);
            if (imageAlt) setMetaTag('og:image:alt', imageAlt);
        }
        setMetaTag('og:url', window.location.href);
        setMetaTag('og:site_name', 'Watchlistey');
        setMetaTag('og:locale', i18n.language);

        // Cleanup function to reset title when component unmounts
        return () => {
            document.title = originalTitle;
            if (originalDesc) metaDesc?.setAttribute('content', originalDesc);
            if (originalCanonical) linkCanonical?.setAttribute('href', originalCanonical || '');
            
            // Clean up hreflangs generated by this hook instance
            const cleanupHreflangs = document.querySelectorAll("link[rel='alternate'][hreflang]");
            cleanupHreflangs.forEach(el => el.remove());
        };
    }, [title, description, image, imageAlt, skipSuffix, t, i18n.language]);
};
